# header file auto generated by fbdoc and plugin py_ctypes.bas
# to be inported by libpruio.py (do not change)
from ctypesloader import *

_libs = {}
_libs['pruio'] = load_library('pruio')

# pruio_pins.bi: 14
try: P8_03 = 0x06
except: pass

# pruio_pins.bi: 16
try: P8_04 = 0x07
except: pass

# pruio_pins.bi: 18
try: P8_05 = 0x02
except: pass

# pruio_pins.bi: 20
try: P8_06 = 0x03
except: pass

# pruio_pins.bi: 22
try: P8_07 = 0x24
except: pass

# pruio_pins.bi: 24
try: P8_08 = 0x25 
except: pass

# pruio_pins.bi: 26
try: P8_09 = 0x27 
except: pass

# pruio_pins.bi: 28
try: P8_10 = 0x26 
except: pass

# pruio_pins.bi: 30
try: P8_11 = 0x0D 
except: pass

# pruio_pins.bi: 32
try: P8_12 = 0x0C 
except: pass

# pruio_pins.bi: 34
try: P8_13 = 0x09 
except: pass

# pruio_pins.bi: 36
try: P8_14 = 0x0A 
except: pass

# pruio_pins.bi: 38
try: P8_15 = 0x0F 
except: pass

# pruio_pins.bi: 40
try: P8_16 = 0x0E 
except: pass

# pruio_pins.bi: 42
try: P8_17 = 0x0B 
except: pass

# pruio_pins.bi: 44
try: P8_18 = 0x23 
except: pass

# pruio_pins.bi: 46
try: P8_19 = 0x08 
except: pass

# pruio_pins.bi: 48
try: P8_20 = 0x21 
except: pass

# pruio_pins.bi: 50
try: P8_21 = 0x20 
except: pass

# pruio_pins.bi: 52
try: P8_22 = 0x05 
except: pass

# pruio_pins.bi: 54
try: P8_23 = 0x04 
except: pass

# pruio_pins.bi: 56
try: P8_24 = 0x01 
except: pass

# pruio_pins.bi: 58
try: P8_25 = 0x00 
except: pass

# pruio_pins.bi: 60
try: P8_26 = 0x1F 
except: pass

# pruio_pins.bi: 62
try: P8_27 = 0x38 
except: pass

# pruio_pins.bi: 64
try: P8_28 = 0x3A 
except: pass

# pruio_pins.bi: 66
try: P8_29 = 0x39 
except: pass

# pruio_pins.bi: 68
try: P8_30 = 0x3B 
except: pass

# pruio_pins.bi: 70
try: P8_31 = 0x36 
except: pass

# pruio_pins.bi: 72
try: P8_32 = 0x37 
except: pass

# pruio_pins.bi: 74
try: P8_33 = 0x35 
except: pass

# pruio_pins.bi: 76
try: P8_34 = 0x33 
except: pass

# pruio_pins.bi: 78
try: P8_35 = 0x34 
except: pass

# pruio_pins.bi: 80
try: P8_36 = 0x32 
except: pass

# pruio_pins.bi: 82
try: P8_37 = 0x30 
except: pass

# pruio_pins.bi: 84
try: P8_38 = 0x31 
except: pass

# pruio_pins.bi: 86
try: P8_39 = 0x2E 
except: pass

# pruio_pins.bi: 88
try: P8_40 = 0x2F 
except: pass

# pruio_pins.bi: 90
try: P8_41 = 0x2C 
except: pass

# pruio_pins.bi: 92
try: P8_42 = 0x2D 
except: pass

# pruio_pins.bi: 94
try: P8_43 = 0x2A 
except: pass

# pruio_pins.bi: 96
try: P8_44 = 0x2B 
except: pass

# pruio_pins.bi: 98
try: P8_45 = 0x28 
except: pass

# pruio_pins.bi: 100
try: P8_46 = 0x29 
except: pass

# pruio_pins.bi: 103
try: P9_11 = 0x1C 
except: pass

# pruio_pins.bi: 105
try: P9_12 = 0x1E 
except: pass

# pruio_pins.bi: 107
try: P9_13 = 0x1D 
except: pass

# pruio_pins.bi: 109
try: P9_14 = 0x12 
except: pass

# pruio_pins.bi: 111
try: P9_15 = 0x10 
except: pass

# pruio_pins.bi: 113
try: P9_16 = 0x13 
except: pass

# pruio_pins.bi: 115
try: P9_17 = 0x57 
except: pass

# pruio_pins.bi: 117
try: P9_18 = 0x56 
except: pass

# pruio_pins.bi: 119
try: P9_19 = 0x5F 
except: pass

# pruio_pins.bi: 121
try: P9_20 = 0x5E 
except: pass

# pruio_pins.bi: 123
try: P9_21 = 0x55 
except: pass

# pruio_pins.bi: 125
try: P9_22 = 0x54 
except: pass

# pruio_pins.bi: 127
try: P9_23 = 0x11 
except: pass

# pruio_pins.bi: 129
try: P9_24 = 0x61 
except: pass

# pruio_pins.bi: 131
try: P9_25 = 0x6B 
except: pass

# pruio_pins.bi: 133
try: P9_26 = 0x60 
except: pass

# pruio_pins.bi: 135
try: P9_27 = 0x69 
except: pass

# pruio_pins.bi: 137
try: P9_28 = 0x67 
except: pass

# pruio_pins.bi: 139
try: P9_29 = 0x65 
except: pass

# pruio_pins.bi: 141
try: P9_30 = 0x66 
except: pass

# pruio_pins.bi: 143
try: P9_31 = 0x64 
except: pass

# pruio_pins.bi: 146
try: P9_33 = no_pinmuxing_for_AIN4
except: pass

# pruio_pins.bi: 148
try: P9_35 = no_pinmuxing_for_AIN6
except: pass

# pruio_pins.bi: 150
try: P9_36 = no_pinmuxing_for_AIN5
except: pass

# pruio_pins.bi: 152
try: P9_37 = no_pinmuxing_for_AIN2
except: pass

# pruio_pins.bi: 154
try: P9_38 = no_pinmuxing_for_AIN3
except: pass

# pruio_pins.bi: 156
try: P9_39 = no_pinmuxing_for_AIN0
except: pass

# pruio_pins.bi: 158
try: P9_40 = no_pinmuxing_for_AIN1
except: pass

# pruio_pins.bi: 161
try: P9_41 = 0x6D 
except: pass

# pruio_pins.bi: 163
try: P9_42 = 0x59 
except: pass

# pruio_pins.bi: 166
try: JT_04 = 0x5C 
except: pass

# pruio_pins.bi: 168
try: JT_05 = 0x5D 
except: pass

# pruio_pins.bi: 171
try: SD_01 = 0x3D 
except: pass

# pruio_pins.bi: 173
try: SD_02 = 0x3C 
except: pass

# pruio_pins.bi: 175
try: SD_03 = 0x41 
except: pass

# pruio_pins.bi: 177
try: SD_05 = 0x40 
except: pass

# pruio_pins.bi: 179
try: SD_07 = 0x3F 
except: pass

# pruio_pins.bi: 181
try: SD_08 = 0x3E 
except: pass

# pruio_pins.bi: 183
try: SD_10 = 0x58 
except: pass


# pruio_pins_blue.bi: 14
try: E1_3 = 0x68 
except: pass

# pruio_pins_blue.bi: 16
try: E1_4 = 0x69 
except: pass

# pruio_pins_blue.bi: 18
try: E2_3 = 0x34 
except: pass

# pruio_pins_blue.bi: 20
try: E2_4 = 0x35 
except: pass

# pruio_pins_blue.bi: 22
try: E3_3 = 0x0C 
except: pass

# pruio_pins_blue.bi: 24
try: E3_4 = 0x0D 
except: pass

# pruio_pins_blue.bi: 26
try: E4_3 = 0x0E 
except: pass

# pruio_pins_blue.bi: 28
try: E4_4 = 0x0F 
except: pass

# pruio_pins_blue.bi: 30
try: UT0_3 = 0x5C 
except: pass

# pruio_pins_blue.bi: 32
try: UT0_4 = 0x5D 
except: pass

# pruio_pins_blue.bi: 34
try: UT1_3 = 0x60 
except: pass

# pruio_pins_blue.bi: 36
try: UT1_4 = 0x61 
except: pass

# pruio_pins_blue.bi: 38
try: UT5_3 = 0x31 
except: pass

# pruio_pins_blue.bi: 40
try: UT5_4 = 0x30 
except: pass

# pruio_pins_blue.bi: 42
try: DSM2_3 = 0x1C 
except: pass

# pruio_pins_blue.bi: 44
try: GP0_3 = 0x19 
except: pass

# pruio_pins_blue.bi: 46
try: GP0_4 = 0x11 
except: pass

# pruio_pins_blue.bi: 48
try: GP0_5 = 0x6A 
except: pass

# pruio_pins_blue.bi: 50
try: GP0_6 = 0x67 
except: pass

# pruio_pins_blue.bi: 52
try: GP1_3 = 0x44 
except: pass

# pruio_pins_blue.bi: 54
try: GP1_4 = 0x43 
except: pass

# pruio_pins_blue.bi: 56
try: GP1_5 = 0x24 
except: pass

# pruio_pins_blue.bi: 58
try: GP1_6 = 0x25 
except: pass

# pruio_pins_blue.bi: 60
try: GPS_3 = 0x54 
except: pass

# pruio_pins_blue.bi: 62
try: GPS_4 = 0x55 
except: pass

# pruio_pins_blue.bi: 64
try: SPI1_3 = 0x66 
except: pass

# pruio_pins_blue.bi: 66
try: SPI1_4 = 0x65 
except: pass

# pruio_pins_blue.bi: 68
try: SPI1_5 = 0x64 
except: pass

# pruio_pins_blue.bi: 70
try: SPI1_6 = 0x51 
except: pass

# pruio_pins_blue.bi: 72
try: SPI2_6 = 0x59 
except: pass


# pruio_pins_pocket.bi: 16
try: P1_02 = 0x39 
except: pass

# pruio_pins_pocket.bi: 19
try: P1_04 = 0x3B 
except: pass

# pruio_pins_pocket.bi: 22
try: P1_06 = 0x57 
except: pass

# pruio_pins_pocket.bi: 25
try: P1_08 = 0x54 
except: pass

# pruio_pins_pocket.bi: 28
try: P1_10 = 0x55 
except: pass

# pruio_pins_pocket.bi: 31
try: P1_12 = 0x56 
except: pass

# pruio_pins_pocket.bi: 39
try: P1_19 = no_pinmuxing_for_AIN0
except: pass

# pruio_pins_pocket.bi: 41
try: P1_20 = 0x6D 
except: pass

# pruio_pins_pocket.bi: 43
try: P1_21 = no_pinmuxing_for_AIN1
except: pass

# pruio_pins_pocket.bi: 46
try: P1_23 = no_pinmuxing_for_AIN2
except: pass

# pruio_pins_pocket.bi: 49
try: P1_25 = no_pinmuxing_for_AIN3
except: pass

# pruio_pins_pocket.bi: 51
try: P1_26 = 0x5E 
except: pass

# pruio_pins_pocket.bi: 53
try: P1_27 = no_pinmuxing_for_AIN4
except: pass

# pruio_pins_pocket.bi: 55
try: P1_28 = 0x5F 
except: pass

# pruio_pins_pocket.bi: 57
try: P1_29 = 0x6B 
except: pass

# pruio_pins_pocket.bi: 59
try: P1_30 = 0x5D 
except: pass

# pruio_pins_pocket.bi: 61
try: P1_31 = 0x68 
except: pass

# pruio_pins_pocket.bi: 63
try: P1_32 = 0x5C 
except: pass

# pruio_pins_pocket.bi: 65
try: P1_33 = 0x65 
except: pass

# pruio_pins_pocket.bi: 67
try: P1_34 = 0x0A 
except: pass

# pruio_pins_pocket.bi: 69
try: P1_35 = 0x3A 
except: pass

# pruio_pins_pocket.bi: 71
try: P1_36 = 0x64 
except: pass

# pruio_pins_pocket.bi: 75
try: P2_01 = 0x12 
except: pass

# pruio_pins_pocket.bi: 77
try: P2_02 = 0x1E 
except: pass

# pruio_pins_pocket.bi: 79
try: P2_03 = 0x09 
except: pass

# pruio_pins_pocket.bi: 81
try: P2_04 = 0x1D 
except: pass

# pruio_pins_pocket.bi: 83
try: P2_05 = 0x1C 
except: pass

# pruio_pins_pocket.bi: 85
try: P2_06 = 0x19 
except: pass

# pruio_pins_pocket.bi: 87
try: P2_07 = 0x1D 
except: pass

# pruio_pins_pocket.bi: 89
try: P2_08 = 0x1E 
except: pass

# pruio_pins_pocket.bi: 91
try: P2_09 = 0x61 
except: pass

# pruio_pins_pocket.bi: 93
try: P2_10 = 0x14 
except: pass

# pruio_pins_pocket.bi: 95
try: P2_11 = 0x60 
except: pass

# pruio_pins_pocket.bi: 102
try: P2_17 = 0x23 
except: pass

# pruio_pins_pocket.bi: 104
try: P2_18 = 0x0F 
except: pass

# pruio_pins_pocket.bi: 106
try: P2_19 = 0x0B 
except: pass

# pruio_pins_pocket.bi: 108
try: P2_20 = 0x22 
except: pass

# pruio_pins_pocket.bi: 110
try: P2_22 = 0x0E 
except: pass

# pruio_pins_pocket.bi: 113
try: P2_24 = 0x0C 
except: pass

# pruio_pins_pocket.bi: 115
try: P2_25 = 0x5B 
except: pass

# pruio_pins_pocket.bi: 118
try: P2_27 = 0x5A 
except: pass

# pruio_pins_pocket.bi: 120
try: P2_28 = 0x6D 
except: pass

# pruio_pins_pocket.bi: 122
try: P2_29 = 0x59 
except: pass

# pruio_pins_pocket.bi: 124
try: P2_30 = 0x67 
except: pass

# pruio_pins_pocket.bi: 126
try: P2_31 = 0x6C 
except: pass

# pruio_pins_pocket.bi: 128
try: P2_32 = 0x66 
except: pass

# pruio_pins_pocket.bi: 130
try: P2_33 = 0x0D 
except: pass

# pruio_pins_pocket.bi: 132
try: P2_34 = 0x69 
except: pass

# pruio_pins_pocket.bi: 134
try: P2_35 = 0x38 
except: pass

# pruio_pins_pocket.bi: 136
try: P2_36 = no_pinmuxing_for_AIN7
except: pass

# pruio_pins_pocket.bi: 139
try: SD_01 = 0x3D 
except: pass

# pruio_pins_pocket.bi: 141
try: SD_02 = 0x3C 
except: pass

# pruio_pins_pocket.bi: 143
try: SD_03 = 0x41 
except: pass

# pruio_pins_pocket.bi: 145
try: SD_05 = 0x40 
except: pass

# pruio_pins_pocket.bi: 147
try: SD_07 = 0x3F 
except: pass

# pruio_pins_pocket.bi: 149
try: SD_08 = 0x3E 
except: pass

# pruio_pins_pocket.bi: 151
try: SD_10 = 0x58 
except: pass


# pruio.hp: 106
try: PRUIO_IRPT = 25
except: pass

# pruio.hp: 107
try: IRPT = PRUIO_IRPT + 16
except: pass

# pruio.hp: 108
try: CTBIR = 0x22020
except: pass

# pruio.hp: 109
try: CONST_PRUCFG = C4
except: pass

# pruio.hp: 110
try: DRam = C24
except: pass

# pruio.hp: 112
try: PRUIO_AZ_BALL = 109
except: pass

# pruio.hp: 113
try: PRUIO_AZ_GPIO = 3
except: pass

# pruio.hp: 114
try: PRUIO_AZ_PWMSS = 2
except: pass

# pruio.hp: 115
try: PRUIO_AZ_TIMER = 3
except: pass

# pruio.hp: 117
try: PRUIO_COM_POKE = 10
except: pass

# pruio.hp: 118
try: PRUIO_COM_PEEK = 9
except: pass

# pruio.hp: 119
try: PRUIO_COM_GPIO_CONF = 20
except: pass

# pruio.hp: 120
try: PRUIO_COM_PWM = 30
except: pass

# pruio.hp: 121
try: PRUIO_COM_CAP_PWM = 29
except: pass

# pruio.hp: 122
try: PRUIO_COM_CAP = 28
except: pass

# pruio.hp: 123
try: PRUIO_COM_QEP = 27
except: pass

# pruio.hp: 124
try: PRUIO_COM_CAP_TIM = 26
except: pass

# pruio.hp: 125
try: PRUIO_COM_TIM_PWM = 40
except: pass

# pruio.hp: 126
try: PRUIO_COM_TIM_TIM = 39
except: pass

# pruio.hp: 127
try: PRUIO_COM_TIM_CAP = 38
except: pass

# pruio.hp: 128
try: PRUIO_COM_ADC = 50
except: pass

# pruio.hp: 130
try: PRUIO_DAT_GPIO = 64
except: pass

# pruio.hp: 131
try: PRUIO_DAT_PWM = 128
except: pass

# pruio.hp: 132
try: PRUIO_DAT_TIMER = 224
except: pass

# pruio.hp: 133
try: PRUIO_DAT_ADC = 288
except: pass

# pruio.hp: 134
try: PRUIO_DAT_ALL = 512
except: pass

# pruio.hp: 136
try: PRUIO_MSG_INIT_RUN = 4294967295
except: pass

# pruio.hp: 137
try: PRUIO_MSG_CONF_RUN = 4294967294
except: pass

# pruio.hp: 138
try: PRUIO_MSG_INIT_OK = 4294967293
except: pass

# pruio.hp: 139
try: PRUIO_MSG_CONF_OK = 4294967292
except: pass

# pruio.hp: 140
try: PRUIO_MSG_ADC_ERRR = 4294967291
except: pass

# pruio.hp: 141
try: PRUIO_MSG_MM_WAIT = 4294967290
except: pass

# pruio.hp: 142
try: PRUIO_MSG_MM_TRG1 = 4294967289
except: pass

# pruio.hp: 143
try: PRUIO_MSG_MM_TRG2 = 4294967288
except: pass

# pruio.hp: 144
try: PRUIO_MSG_MM_TRG3 = 4294967287
except: pass

# pruio.hp: 145
try: PRUIO_MSG_MM_TRG4 = 4294967286
except: pass

# pruio.hp: 146
try: PRUIO_MSG_IO_OK = 4294967285
except: pass


# pruio_globals.bi: 15
try: NULL = 0
except: pass

# pruio_globals.bi: 18
try: PRUIO_DEF_AVRAGE = 4
except: pass

# pruio_globals.bi: 20
try: PRUIO_DEF_ODELAY = 183
except: pass

# pruio_globals.bi: 22
try: PRUIO_DEF_SDELAY = 0
except: pass

# pruio_globals.bi: 24
try: PRUIO_DEF_SAMPLS = 1
except: pass

# pruio_globals.bi: 26
try: PRUIO_DEF_STPMSK = 0b111111110
except: pass

# pruio_globals.bi: 28
try: PRUIO_DEF_TIMERV = 0
except: pass

# pruio_globals.bi: 30
try: PRUIO_DEF_LSLMOD = 4
except: pass

# pruio_globals.bi: 32
try: PRUIO_DEF_CLKDIV = 0
except: pass

# pruio_globals.bi: 41
Int8 = c_byte

# pruio_globals.bi: 42
Int16 = c_short

# pruio_globals.bi: 43
Int32 = c_long

# pruio_globals.bi: 44
UInt8 = c_ubyte

# pruio_globals.bi: 45
UInt16 = c_ushort

# pruio_globals.bi: 46
UInt32 = c_ulong

# pruio_globals.bi: 47
Float_t = c_float

# pruio_globals.bi: 49
class PruIo(Structure):
  pass
Pruio_ = PruIo

# pruio_globals.bi: 50
class AdcUdt(Structure):
  pass
AdcUdt_ = AdcUdt

# pruio_globals.bi: 51
class GpioUdt(Structure):
  pass
GpioUdt_ = GpioUdt

# pruio_globals.bi: 52
class PwmssUdt(Structure):
  pass
PwmssUdt_ = PwmssUdt

# pruio_globals.bi: 53
class PwmMod(Structure):
  pass
PwmMod_ = PwmMod

# pruio_globals.bi: 54
class CapMod(Structure):
  pass
CapMod_ = CapMod

# pruio_globals.bi: 55
class QepMod(Structure):
  pass
QepMod_ = QepMod

# pruio_globals.bi: 56
class TimerUdt(Structure):
  pass
TimerUdt_ = TimerUdt

# pruio_globals.bi: 70
try: PRUIO_PULL_DOWN = 0b000000 
except: pass
try: PRUIO_NO_PULL = 0b001000 
except: pass
try: PRUIO_PULL_UP = 0b010000 
except: pass
try: PRUIO_RX_ACTIV = 0b100000 
except: pass
try: PRUIO_GPIO_OUT0 = 7 + PRUIO_NO_PULL                    
except: pass
try: PRUIO_GPIO_OUT1 = 7 + PRUIO_NO_PULL + 128              
except: pass
try: PRUIO_GPIO_IN = 7 + PRUIO_NO_PULL + PRUIO_RX_ACTIV   
except: pass
try: PRUIO_GPIO_IN_0 = 7 + PRUIO_PULL_DOWN + PRUIO_RX_ACTIV 
except: pass
try: PRUIO_GPIO_IN_1 = 7 + PRUIO_PULL_UP + PRUIO_RX_ACTIV   
except: pass
try: PRUIO_PIN_RESET = 0xFF
except: pass


# pruio_adc.bi: 27

class AdcSteps(Structure):
  pass 
AdcSteps._fields_ = [
  ('Confg', UInt32),
  ('Delay', UInt32),
]

# pruio_adc.bi: 71

class AdcSet(Structure):
  pass 
AdcSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('REVISION', UInt32),
  ('SYSCONFIG', UInt32),
  ('IRQSTATUS_RAW', UInt32),
  ('IRQSTATUS', UInt32),
  ('IRQENABLE_SET', UInt32),
  ('IRQENABLE_CLR', UInt32),
  ('IRQWAKEUP', UInt32),
  ('DMAENABLE_SET', UInt32),
  ('DMAENABLE_CLR', UInt32),
  ('CTRL', UInt32),
  ('ADCSTAT', UInt32),
  ('ADCRANGE', UInt32),
  ('ADC_CLKDIV', UInt32),
  ('ADC_MISC', UInt32),
  ('STEPENABLE', UInt32),
  ('IDLECONFIG', UInt32),
  ('St_p', AdcSteps * (16 + 1)),
  ('FIFO0COUNT', UInt32),
  ('FIFO0THRESHOLD', UInt32),
  ('DMA0REQ', UInt32),
  ('FIFO1COUNT', UInt32),
  ('FIFO1THRESHOLD', UInt32),
  ('DMA1REQ', UInt32),
]

# pruio_adc.bi: 132
AdcUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(AdcSet)),
  ('Conf', POINTER(AdcSet)),
  ('Samples', UInt32),
  ('TimerVal', UInt32),
  ('InitParA', UInt32),
  ('LslMode', UInt16),
  ('ChAz', UInt16),
  ('Value', POINTER(UInt16)),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
  ('E3', c_char_p),
  ('E4', c_char_p),
  ('E5', c_char_p),
]


# pruio_gpio.bi: 54

class GpioSet(Structure):
  pass 
GpioSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('REVISION', UInt32),
  ('SYSCONFIG', UInt32),
  ('EOI', UInt32),
  ('IRQSTATUS_RAW_0', UInt32),
  ('IRQSTATUS_RAW_1', UInt32),
  ('IRQSTATUS_0', UInt32),
  ('IRQSTATUS_1', UInt32),
  ('IRQSTATUS_SET_0', UInt32),
  ('IRQSTATUS_SET_1', UInt32),
  ('IRQSTATUS_CLR_0', UInt32),
  ('IRQSTATUS_CLR_1', UInt32),
  ('IRQWAKEN_0', UInt32),
  ('IRQWAKEN_1', UInt32),
  ('SYSSTATUS', UInt32),
  ('CTRL', UInt32),
  ('OE', UInt32),
  ('DATAIN', UInt32),
  ('DATAOUT', UInt32),
  ('LEVELDETECT0', UInt32),
  ('LEVELDETECT1', UInt32),
  ('RISINGDETECT', UInt32),
  ('FALLINGDETECT', UInt32),
  ('DEBOUNCENABLE', UInt32),
  ('DEBOUNCINGTIME', UInt32),
  ('CLEARDATAOUT', UInt32),
  ('SETDATAOUT', UInt32),
]

# pruio_gpio.bi: 70

class GpioArr(Structure):
  pass 
GpioArr._fields_ = [
  ('DeAd', UInt32),
  ('DATAIN', UInt32),
  ('DATAOUT', UInt32),
  ('Mix', UInt32),
]

# pruio_gpio.bi: 113
GpioUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(GpioSet) * (PRUIO_AZ_GPIO + 1)),
  ('Conf', POINTER(GpioSet) * (PRUIO_AZ_GPIO + 1)),
  ('Raw', POINTER(GpioArr) * (PRUIO_AZ_GPIO + 1)),
  ('InitParA', UInt32),
  ('Mask', UInt32),
  ('Mode', UInt8),
  ('Indx', UInt8),
  ('Fe1', UInt8),
  ('Fe2', UInt8),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
]


# pruio_pwmss.bi: 132

class PwmssSet(Structure):
  pass 
PwmssSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('IDVER', UInt32),
  ('SYSCONFIG', UInt32),
  ('CLKCONFIG', UInt32),
  ('CLKSTATUS', UInt32),
  ('TSCTR', UInt32),
  ('CTRPHS', UInt32),
  ('CAP1', UInt32),
  ('CAP2', UInt32),
  ('CAP3', UInt32),
  ('CAP4', UInt32),
  ('ECCTL1', UInt16),
  ('ECCTL2', UInt16),
  ('ECEINT', UInt16),
  ('ECFLG', UInt16),
  ('ECCLR', UInt16),
  ('ECFRC', UInt16),
  ('CAP_REV', UInt32),
  ('QPOSCNT', UInt32),
  ('QPOSINIT', UInt32),
  ('QPOSMAX', UInt32),
  ('QPOSCMP', UInt32),
  ('QPOSILAT', UInt32),
  ('QPOSSLAT', UInt32),
  ('QPOSLAT', UInt32),
  ('QUTMR', UInt32),
  ('QUPRD', UInt32),
  ('QWDTMR', UInt16),
  ('QWDPRD', UInt16),
  ('QDECCTL', UInt16),
  ('QEPCTL', UInt16),
  ('QCAPCTL', UInt16),
  ('QPOSCTL', UInt16),
  ('QEINT', UInt16),
  ('QFLG', UInt16),
  ('QCLR', UInt16),
  ('QFRC', UInt16),
  ('QEPSTS', UInt16),
  ('QCTMR', UInt16),
  ('QCPRD', UInt16),
  ('QCTMRLAT', UInt16),
  ('QCPRDLAT', UInt16),
  ('empty', UInt16),
  ('QEP_REV', UInt32),
  ('TBCTL', UInt16),
  ('TBSTS', UInt16),
  ('TBPHSHR', UInt16),
  ('TBPHS', UInt16),
  ('TBCNT', UInt16),
  ('TBPRD', UInt16),
  ('CMPCTL', UInt16),
  ('CMPAHR', UInt16),
  ('CMPA', UInt16),
  ('CMPB', UInt16),
  ('AQCTLA', UInt16),
  ('AQCTLB', UInt16),
  ('AQSFRC', UInt16),
  ('AQCSFRC', UInt16),
  ('DBCTL', UInt16),
  ('DBRED', UInt16),
  ('DBFED', UInt16),
  ('TZSEL', UInt16),
  ('TZCTL', UInt16),
  ('TZEINT', UInt16),
  ('TZFLG', UInt16),
  ('TZCLR', UInt16),
  ('TZFRC', UInt16),
  ('ETSEL', UInt16),
  ('ETPS', UInt16),
  ('ETFLG', UInt16),
  ('ETCLR', UInt16),
  ('ETFRC', UInt16),
  ('PCCTL', UInt16),
  ('HRCTL', UInt16),
]

# pruio_pwmss.bi: 153

class PwmssArr(Structure):
  pass 
PwmssArr._fields_ = [
  ('DeAd', UInt32),
  ('CMax', UInt32),
  ('C1', UInt32),
  ('C2', UInt32),
  ('QPos', UInt32),
  ('NPos', UInt32),
  ('OPos', UInt32),
  ('PLat', UInt32),
]

# pruio_pwmss.bi: 217
PwmssUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(PwmssSet) * (PRUIO_AZ_PWMSS + 1)),
  ('Conf', POINTER(PwmssSet) * (PRUIO_AZ_PWMSS + 1)),
  ('Raw', POINTER(PwmssArr) * (PRUIO_AZ_PWMSS + 1)),
  ('InitParA', UInt32),
  ('PwmMode', UInt16),
  ('CapMode', UInt16),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
  ('E3', c_char_p),
  ('E4', c_char_p),
  ('E5', c_char_p),
  ('E6', c_char_p),
  ('E7', c_char_p),
  ('E8', c_char_p),
  ('E9', c_char_p),
]

# pruio_pwmss.bi: 265
PwmMod._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('ForceUpDown', UInt16),
  ('Cntrl', UInt16 * (PRUIO_AZ_PWMSS + 1)),
  ('AqCtl', UInt16 * ((1 + 1) * (PRUIO_AZ_PWMSS + 1) * (2 + 1))),
]

# pruio_pwmss.bi: 292
CapMod._fields_ = [
  ('Top', POINTER(Pruio_)),
]

# pruio_pwmss.bi: 323
QepMod._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('FVh', Float_t * (PRUIO_AZ_PWMSS + 1)),
  ('FVl', Float_t * (PRUIO_AZ_PWMSS + 1)),
  ('Prd', UInt32 * (PRUIO_AZ_PWMSS + 1)),
]


# pruio_timer.bi: 45

class TimerSet(Structure):
  pass 
TimerSet._fields_ = [
  ('DeAd', UInt32),
  ('ClAd', UInt32),
  ('ClVa', UInt32),
  ('TIDR', UInt32),
  ('TIOCP_CFG', UInt32),
  ('IRQ_EOI', UInt32),
  ('IRQSTATUS_RAW', UInt32),
  ('IRQSTATUS', UInt32),
  ('IRQENABLE_SET', UInt32),
  ('IRQENABLE_CLR', UInt32),
  ('IRQWAKEEN', UInt32),
  ('TCLR', UInt32),
  ('TCRR', UInt32),
  ('TLDR', UInt32),
  ('TTGR', UInt32),
  ('TWPS', UInt32),
  ('TMAR', UInt32),
  ('TCAR1', UInt32),
  ('TSICR', UInt32),
  ('TCAR2', UInt32),
]

# pruio_timer.bi: 61

class TimerArr(Structure):
  pass 
TimerArr._fields_ = [
  ('DeAd', UInt32),
  ('CMax', UInt32),
  ('TCAR1', UInt32),
  ('TCAR2', UInt32),
]

# pruio_timer.bi: 119
TimerUdt._fields_ = [
  ('Top', POINTER(Pruio_)),
  ('Init', POINTER(TimerSet) * (PRUIO_AZ_TIMER + 1)),
  ('Conf', POINTER(TimerSet) * (PRUIO_AZ_TIMER + 1)),
  ('Raw', POINTER(TimerArr) * (PRUIO_AZ_TIMER + 1)),
  ('InitParA', UInt32),
  ('PwmMode', UInt32),
  ('TimMode', UInt32),
  ('TimHigh', UInt32),
  ('Tim_Low', UInt32),
  ('CapMode', UInt32),
  ('E0', c_char_p),
  ('E1', c_char_p),
  ('E2', c_char_p),
  ('E3', c_char_p),
  ('E4', c_char_p),
  ('E5', c_char_p),
]


# pruio_intc.bi: 13
try: PRU0_PRU1_INTERRUPT = 17
except: pass

# pruio_intc.bi: 15
try: PRU1_PRU0_INTERRUPT = 18
except: pass

# pruio_intc.bi: 17
try: PRU0_ARM_INTERRUPT = 19
except: pass

# pruio_intc.bi: 19
try: PRU1_ARM_INTERRUPT = 20
except: pass

# pruio_intc.bi: 21
try: ARM_PRU0_INTERRUPT = 21
except: pass

# pruio_intc.bi: 23
try: ARM_PRU1_INTERRUPT = 22
except: pass

# pruio_intc.bi: 26
try: CHANNEL0 = 0
except: pass

# pruio_intc.bi: 28
try: CHANNEL1 = 1
except: pass

# pruio_intc.bi: 30
try: CHANNEL2 = 2
except: pass

# pruio_intc.bi: 32
try: CHANNEL3 = 3
except: pass

# pruio_intc.bi: 34
try: CHANNEL4 = 4
except: pass

# pruio_intc.bi: 36
try: CHANNEL5 = 5
except: pass

# pruio_intc.bi: 38
try: CHANNEL6 = 6
except: pass

# pruio_intc.bi: 40
try: CHANNEL7 = 7
except: pass

# pruio_intc.bi: 42
try: CHANNEL8 = 8
except: pass

# pruio_intc.bi: 44
try: CHANNEL9 = 9
except: pass

# pruio_intc.bi: 46
try: PRU0 = 0
except: pass

# pruio_intc.bi: 48
try: PRU1 = 1
except: pass

# pruio_intc.bi: 50
try: PRU_EVTOUT0 = 2
except: pass

# pruio_intc.bi: 52
try: PRU_EVTOUT1 = 3
except: pass

# pruio_intc.bi: 54
try: PRU_EVTOUT2 = 4
except: pass

# pruio_intc.bi: 56
try: PRU_EVTOUT3 = 5
except: pass

# pruio_intc.bi: 58
try: PRU_EVTOUT4 = 6
except: pass

# pruio_intc.bi: 60
try: PRU_EVTOUT5 = 7
except: pass

# pruio_intc.bi: 62
try: PRU_EVTOUT6 = 8
except: pass

# pruio_intc.bi: 64
try: PRU_EVTOUT7 = 9
except: pass

# pruio_intc.bi: 66
try: PRU0_HOSTEN_MASK = 0x0001
except: pass

# pruio_intc.bi: 68
try: PRU1_HOSTEN_MASK = 0x0002
except: pass

# pruio_intc.bi: 70
try: PRU_EVTOUT0_HOSTEN_MASK = 0x0004
except: pass

# pruio_intc.bi: 72
try: PRU_EVTOUT1_HOSTEN_MASK = 0x0008
except: pass

# pruio_intc.bi: 74
try: PRU_EVTOUT2_HOSTEN_MASK = 0x0010
except: pass

# pruio_intc.bi: 76
try: PRU_EVTOUT3_HOSTEN_MASK = 0x0020
except: pass

# pruio_intc.bi: 78
try: PRU_EVTOUT4_HOSTEN_MASK = 0x0040
except: pass

# pruio_intc.bi: 80
try: PRU_EVTOUT5_HOSTEN_MASK = 0x0080
except: pass

# pruio_intc.bi: 82
try: PRU_EVTOUT6_HOSTEN_MASK = 0x0100
except: pass

# pruio_intc.bi: 84
try: PRU_EVTOUT7_HOSTEN_MASK = 0x0200
except: pass

# pruio_intc.bi: 110
try: NUM_PRU_HOSTIRQS = 8
except: pass

# pruio_intc.bi: 112
try: NUM_PRU_HOSTS = 10
except: pass

# pruio_intc.bi: 114
try: NUM_PRU_CHANNELS = 10
except: pass

# pruio_intc.bi: 116
try: NUM_PRU_SYS_EVTS = 64
except: pass

# pruio_intc.bi: 118
try: PRUSS0_PRU0_DRAM = 0
except: pass

# pruio_intc.bi: 120
try: PRUSS0_PRU1_DRAM = 1
except: pass

# pruio_intc.bi: 122
try: PRUSS0_PRU0_IRAM = 2
except: pass

# pruio_intc.bi: 124
try: PRUSS0_PRU1_IRAM = 3
except: pass

# pruio_intc.bi: 126
try: PRUSS0_SRAM = 4
except: pass

# pruio_intc.bi: 140
try: PRU_EVTOUT_0 = 0
except: pass

# pruio_intc.bi: 142
try: PRU_EVTOUT_1 = 1
except: pass

# pruio_intc.bi: 144
try: PRU_EVTOUT_2 = 2
except: pass

# pruio_intc.bi: 146
try: PRU_EVTOUT_3 = 3
except: pass

# pruio_intc.bi: 148
try: PRU_EVTOUT_4 = 4
except: pass

# pruio_intc.bi: 150
try: PRU_EVTOUT_5 = 5
except: pass

# pruio_intc.bi: 152
try: PRU_EVTOUT_6 = 6
except: pass

# pruio_intc.bi: 154
try: PRU_EVTOUT_7 = 7
except: pass

# pruio_intc.bi: 168

class __Sysevt_to_Channel_map(Structure):
  pass 
__Sysevt_to_Channel_map._fields_ = [
  ('sysevt', Int16),
  ('channel', Int16),
]

# pruio_intc.bi: 171
class __Sysevt_to_Channel_map(Structure):
  pass
tsysevt_to_channel_map = __Sysevt_to_Channel_map

# pruio_intc.bi: 184

class __Channel_to_Host_map(Structure):
  pass 
__Channel_to_Host_map._fields_ = [
  ('channel', Int16),
  ('host', Int16),
]

# pruio_intc.bi: 187
class __Channel_to_Host_map(Structure):
  pass
tchannel_to_host_map = __Channel_to_Host_map

# pruio_intc.bi: 201

class __Pruss_intc_Initdata(Structure):
  pass 
__Pruss_intc_Initdata._fields_ = [
  ('sysevts_enabled', Int8 * (NUM_PRU_SYS_EVTS-1 + 1)),
  ('sysevt_to_channel_map', tsysevt_to_channel_map * (NUM_PRU_SYS_EVTS-1 + 1)),
  ('channel_to_host_map', tchannel_to_host_map * (NUM_PRU_CHANNELS-1 + 1)),
  ('host_enable_bitmask', UInt32),
]

# pruio_intc.bi: 204
class __Pruss_intc_Initdata(Structure):
  pass
tpruss_intc_initdata = __Pruss_intc_Initdata


# pruio.bi: 28
try: PRUIO_CHAN = CHANNEL5
except: pass

# pruio.bi: 30
try: PRUIO_MASK = PRU_EVTOUT5_HOSTEN_MASK
except: pass

# pruio.bi: 32
try: PRUIO_EMAP = PRU_EVTOUT5
except: pass

# pruio.bi: 34
try: PRUIO_EVNT = PRU_EVTOUT_5
except: pass

# pruio.bi: 67
try: AIN0 = 0b000000010 
except: pass
try: AIN1 = 0b000000100 
except: pass
try: AIN2 = 0b000001000 
except: pass
try: AIN3 = 0b000010000 
except: pass
try: AIN4 = 0b000100000 
except: pass
try: AIN5 = 0b001000000 
except: pass
try: AIN6 = 0b010000000 
except: pass
try: AIN7 = 0b100000000 
except: pass

# pruio.bi: 105
try: PRUIO_ACT_PRU1 = 0b0000000000001 
except: pass
try: PRUIO_ACT_ADC = 0b0000000000010 
except: pass
try: PRUIO_ACT_GPIO0 = 0b0000000000100 
except: pass
try: PRUIO_ACT_GPIO1 = 0b0000000001000 
except: pass
try: PRUIO_ACT_GPIO2 = 0b0000000010000 
except: pass
try: PRUIO_ACT_GPIO3 = 0b0000000100000 
except: pass
try: PRUIO_ACT_PWM0 = 0b0000001000000 
except: pass
try: PRUIO_ACT_PWM1 = 0b0000010000000 
except: pass
try: PRUIO_ACT_PWM2 = 0b0000100000000 
except: pass
try: PRUIO_ACT_TIM4 = 0b0001000000000 
except: pass
try: PRUIO_ACT_TIM5 = 0b0010000000000 
except: pass
try: PRUIO_ACT_TIM6 = 0b0100000000000 
except: pass
try: PRUIO_ACT_TIM7 = 0b1000000000000 
except: pass
try: PRUIO_DEF_ACTIVE = 0b1111111111111 
except: pass
try: PRUIO_ACT_FREMUX = 0b1000000000000000 
except: pass

# pruio.bi: 119

class BallSet(Structure):
  pass 
BallSet._fields_ = [
  ('DeAd', UInt32),
  ('Value', UInt8 * (PRUIO_AZ_BALL + 1)),
]

# pruio.bi: 126
setPinFunc = CFUNCTYPE(c_char_p, POINTER(Pruio_), UInt8, UInt8)

# pruio.bi: 303
PruIo._fields_ = [
  ('Errr', c_char_p),
  ('Adc', POINTER(AdcUdt)),
  ('Gpio', POINTER(GpioUdt)),
  ('PwmSS', POINTER(PwmssUdt)),
  ('TimSS', POINTER(TimerUdt)),
  ('Pwm', POINTER(PwmMod)),
  ('Cap', POINTER(CapMod)),
  ('Qep', POINTER(QepMod)),
  ('Tim', POINTER(TimerUdt)),
  ('DRam', POINTER(UInt32)),
  ('Init', POINTER(BallSet)),
  ('Conf', POINTER(BallSet)),
  ('ERam', c_void_p),
  ('DInit', c_void_p),
  ('DConf', c_void_p),
  ('MOffs', c_void_p),
  ('BallInit', POINTER(UInt8)),
  ('BallConf', POINTER(UInt8)),
  ('EAddr', UInt32),
  ('ESize', UInt32),
  ('DSize', UInt32),
  ('PruNo', UInt32),
  ('PruIRam', UInt32),
  ('PruDRam', UInt32),
  ('PruIntNo', UInt32),
  ('ParOffs', Int16),
  ('DevAct', Int16),
  ('BbType', UInt32),
  ('MuxFnr', UInt32),
  ('MuxAcc', c_char_p),
  ('setPin', setPinFunc),
  ('BallGpio', UInt8 * (PRUIO_AZ_BALL + 1)),
  ('IntcInit', tpruss_intc_initdata),
  ('WaitCycles', UInt32),
]


# pruio_prussdrv.bi: 56

class __prussdrv(Structure):
  pass 
__prussdrv._fields_ = [
  ('mmap_fd', Int32),
  ('fd', Int32 * (NUM_PRU_HOSTIRQS - 1 + 1)),
  ('pru0_dataram_base', c_void_p),
  ('pru1_dataram_base', c_void_p),
  ('intc_base', c_void_p),
  ('pru0_control_base', c_void_p),
  ('pru1_control_base', c_void_p),
  ('pru0_iram_base', c_void_p),
  ('pru1_iram_base', c_void_p),
  ('extram_base', c_void_p),
  ('pruss_sharedram_base', c_void_p),
  ('pru0_dataram_phy_base', UInt32),
  ('pru1_dataram_phy_base', UInt32),
  ('intc_phy_base', UInt32),
  ('pru0_control_phy_base', UInt32),
  ('pru1_control_phy_base', UInt32),
  ('pru0_iram_phy_base', UInt32),
  ('pru1_iram_phy_base', UInt32),
  ('pruss_sram_phy_base', UInt32),
  ('pruss_map_size', UInt32),
  ('extram_phys_base', UInt32),
  ('extram_map_size', UInt32),
  ('intc_data', tpruss_intc_initdata),
]

# pruio_prussdrv.bi: 59
class __prussdrv(Structure):
  pass
tprussdrv = __prussdrv

# pruio_prussdrv.bi: 61
if hasattr(_libs['pruio'], 'prussdrv_open'):
  prussdrv_open = _libs['pruio'].prussdrv_open
  prussdrv_open.argtypes = [UInt32]
  prussdrv_open.restype = Int32

# pruio_prussdrv.bi: 62
if hasattr(_libs['pruio'], 'prussdrv_pru_enable'):
  prussdrv_pru_enable = _libs['pruio'].prussdrv_pru_enable
  prussdrv_pru_enable.argtypes = [UInt32, UInt32]
  prussdrv_pru_enable.restype = Int32

# pruio_prussdrv.bi: 63
if hasattr(_libs['pruio'], 'prussdrv_pru_disable'):
  prussdrv_pru_disable = _libs['pruio'].prussdrv_pru_disable
  prussdrv_pru_disable.argtypes = [UInt32]
  prussdrv_pru_disable.restype = Int32

# pruio_prussdrv.bi: 64
if hasattr(_libs['pruio'], 'prussdrv_pru_reset'):
  prussdrv_pru_reset = _libs['pruio'].prussdrv_pru_reset
  prussdrv_pru_reset.argtypes = [UInt32]
  prussdrv_pru_reset.restype = Int32

# pruio_prussdrv.bi: 65
if hasattr(_libs['pruio'], 'prussdrv_pru_resume'):
  prussdrv_pru_resume = _libs['pruio'].prussdrv_pru_resume
  prussdrv_pru_resume.argtypes = [UInt32]
  if sizeof(c_int) == sizeof(c_void_p):
    prussdrv_pru_resume.restype = ReturnString
  else:
    prussdrv_pru_resume.restype = String
    prussdrv_pru_resume.errcheck = ReturnString

# pruio_prussdrv.bi: 70
if hasattr(_libs['pruio'], 'prussdrv_pru_write_memory'):
  prussdrv_pru_write_memory = _libs['pruio'].prussdrv_pru_write_memory
  prussdrv_pru_write_memory.argtypes = [UInt32, UInt32, POINTER(UInt32), UInt32]
  prussdrv_pru_write_memory.restype = Int32

# pruio_prussdrv.bi: 71
if hasattr(_libs['pruio'], 'prussdrv_pruintc_init'):
  prussdrv_pruintc_init = _libs['pruio'].prussdrv_pruintc_init
  prussdrv_pruintc_init.argtypes = [POINTER(tpruss_intc_initdata)]
  prussdrv_pruintc_init.restype = Int32

# pruio_prussdrv.bi: 72
if hasattr(_libs['pruio'], 'prussdrv_pru_send_event'):
  prussdrv_pru_send_event = _libs['pruio'].prussdrv_pru_send_event
  prussdrv_pru_send_event.argtypes = [UInt32]
  prussdrv_pru_send_event.restype = None

# pruio_prussdrv.bi: 73
if hasattr(_libs['pruio'], 'prussdrv_pru_wait_event'):
  prussdrv_pru_wait_event = _libs['pruio'].prussdrv_pru_wait_event
  prussdrv_pru_wait_event.argtypes = [UInt32]
  prussdrv_pru_wait_event.restype = UInt32

# pruio_prussdrv.bi: 74
if hasattr(_libs['pruio'], 'prussdrv_pru_clear_event'):
  prussdrv_pru_clear_event = _libs['pruio'].prussdrv_pru_clear_event
  prussdrv_pru_clear_event.argtypes = [UInt32, UInt32]
  prussdrv_pru_clear_event.restype = None

# pruio_prussdrv.bi: 75
if hasattr(_libs['pruio'], 'prussdrv_map_extmem'):
  prussdrv_map_extmem = _libs['pruio'].prussdrv_map_extmem
  prussdrv_map_extmem.argtypes = [c_void_p]
  prussdrv_map_extmem.restype = None

# pruio_prussdrv.bi: 76
if hasattr(_libs['pruio'], 'prussdrv_extmem_sIze'):
  prussdrv_extmem_sIze = _libs['pruio'].prussdrv_extmem_sIze
  prussdrv_extmem_sIze.argtypes = []
  prussdrv_extmem_sIze.restype = UInt32

# pruio_prussdrv.bi: 77
if hasattr(_libs['pruio'], 'prussdrv_map_prumem'):
  prussdrv_map_prumem = _libs['pruio'].prussdrv_map_prumem
  prussdrv_map_prumem.argtypes = [UInt32, c_void_p]
  prussdrv_map_prumem.restype = Int32

# pruio_prussdrv.bi: 78
if hasattr(_libs['pruio'], 'prussdrv_get_phys_addr'):
  prussdrv_get_phys_addr = _libs['pruio'].prussdrv_get_phys_addr
  prussdrv_get_phys_addr.argtypes = [c_void_p]
  prussdrv_get_phys_addr.restype = UInt32

# pruio_prussdrv.bi: 79
if hasattr(_libs['pruio'], 'prussdrv_exIt'):
  prussdrv_exIt = _libs['pruio'].prussdrv_exIt
  prussdrv_exIt.argtypes = []
  prussdrv_exIt.restype = None


# pruio_c_wrapper.bas: 29
if hasattr(_libs['pruio'], 'pruio_new'):
  pruio_new = _libs['pruio'].pruio_new
  pruio_new.argtypes = [UInt16, UInt8, UInt32, UInt8]
  pruio_new.restype = POINTER(PruIo)

# pruio_c_wrapper.bas: 38
if hasattr(_libs['pruio'], 'pruio_destroy'):
  pruio_destroy = _libs['pruio'].pruio_destroy
  pruio_destroy.argtypes = [POINTER(PruIo)]
  pruio_destroy.restype = None

# pruio_c_wrapper.bas: 51
if hasattr(_libs['pruio'], 'pruio_config'):
  pruio_config = _libs['pruio'].pruio_config
  pruio_config.argtypes = [POINTER(PruIo), UInt32, UInt32, UInt32, UInt16]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_config.restype = ReturnString
  else:
    pruio_config.restype = String
    pruio_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 62
if hasattr(_libs['pruio'], 'pruio_Pin'):
  pruio_Pin = _libs['pruio'].pruio_Pin
  pruio_Pin.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_Pin.restype = ReturnString
  else:
    pruio_Pin.restype = String
    pruio_Pin.errcheck = ReturnString

# pruio_c_wrapper.bas: 75
if hasattr(_libs['pruio'], 'pruio_mm_start'):
  pruio_mm_start = _libs['pruio'].pruio_mm_start
  pruio_mm_start.argtypes = [POINTER(PruIo), UInt32, UInt32, UInt32, UInt32]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_mm_start.restype = ReturnString
  else:
    pruio_mm_start.restype = String
    pruio_mm_start.errcheck = ReturnString

# pruio_c_wrapper.bas: 84
if hasattr(_libs['pruio'], 'pruio_rb_start'):
  pruio_rb_start = _libs['pruio'].pruio_rb_start
  pruio_rb_start.argtypes = [POINTER(PruIo)]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_rb_start.restype = ReturnString
  else:
    pruio_rb_start.restype = String
    pruio_rb_start.errcheck = ReturnString

# pruio_c_wrapper.bas: 99
if hasattr(_libs['pruio'], 'pruio_adc_setStep'):
  pruio_adc_setStep = _libs['pruio'].pruio_adc_setStep
  pruio_adc_setStep.argtypes = [POINTER(PruIo), UInt8, UInt8, UInt8, UInt8, UInt32]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_adc_setStep.restype = ReturnString
  else:
    pruio_adc_setStep.restype = String
    pruio_adc_setStep.errcheck = ReturnString

# pruio_c_wrapper.bas: 111
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_pin'):
  pruio_adc_mm_trg_pin = _libs['pruio'].pruio_adc_mm_trg_pin
  pruio_adc_mm_trg_pin.argtypes = [POINTER(PruIo), UInt8, UInt8, UInt16]
  pruio_adc_mm_trg_pin.restype = UInt32

# pruio_c_wrapper.bas: 124
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_ain'):
  pruio_adc_mm_trg_ain = _libs['pruio'].pruio_adc_mm_trg_ain
  pruio_adc_mm_trg_ain.argtypes = [POINTER(PruIo), UInt8, Int32, UInt8, UInt16]
  pruio_adc_mm_trg_ain.restype = UInt32

# pruio_c_wrapper.bas: 137
if hasattr(_libs['pruio'], 'pruio_adc_mm_trg_pre'):
  pruio_adc_mm_trg_pre = _libs['pruio'].pruio_adc_mm_trg_pre
  pruio_adc_mm_trg_pre.argtypes = [POINTER(PruIo), UInt8, Int32, UInt16, UInt8]
  pruio_adc_mm_trg_pre.restype = UInt32

# pruio_c_wrapper.bas: 149
if hasattr(_libs['pruio'], 'pruio_gpio_config'):
  pruio_gpio_config = _libs['pruio'].pruio_gpio_config
  pruio_gpio_config.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_gpio_config.restype = ReturnString
  else:
    pruio_gpio_config.restype = String
    pruio_gpio_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 160
if hasattr(_libs['pruio'], 'pruio_gpio_setValue'):
  pruio_gpio_setValue = _libs['pruio'].pruio_gpio_setValue
  pruio_gpio_setValue.argtypes = [POINTER(PruIo), UInt8, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_gpio_setValue.restype = ReturnString
  else:
    pruio_gpio_setValue.restype = String
    pruio_gpio_setValue.errcheck = ReturnString

# pruio_c_wrapper.bas: 170
if hasattr(_libs['pruio'], 'pruio_gpio_Value'):
  pruio_gpio_Value = _libs['pruio'].pruio_gpio_Value
  pruio_gpio_Value.argtypes = [POINTER(PruIo), UInt8]
  pruio_gpio_Value.restype = UInt32

# pruio_c_wrapper.bas: 182
if hasattr(_libs['pruio'], 'pruio_cap_config'):
  pruio_cap_config = _libs['pruio'].pruio_cap_config
  pruio_cap_config.argtypes = [POINTER(PruIo), UInt8, Float_t]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_cap_config.restype = ReturnString
  else:
    pruio_cap_config.restype = String
    pruio_cap_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 194
if hasattr(_libs['pruio'], 'pruio_cap_Value'):
  pruio_cap_Value = _libs['pruio'].pruio_cap_Value
  pruio_cap_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_cap_Value.restype = ReturnString
  else:
    pruio_cap_Value.restype = String
    pruio_cap_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 209
if hasattr(_libs['pruio'], 'pruio_qep_config'):
  pruio_qep_config = _libs['pruio'].pruio_qep_config
  pruio_qep_config.argtypes = [POINTER(PruIo), UInt8, UInt32, Float_t, Float_t, UInt8]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_qep_config.restype = ReturnString
  else:
    pruio_qep_config.restype = String
    pruio_qep_config.errcheck = ReturnString

# pruio_c_wrapper.bas: 221
if hasattr(_libs['pruio'], 'pruio_qep_Value'):
  pruio_qep_Value = _libs['pruio'].pruio_qep_Value
  pruio_qep_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(UInt32), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_qep_Value.restype = ReturnString
  else:
    pruio_qep_Value.restype = String
    pruio_qep_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 234
if hasattr(_libs['pruio'], 'pruio_pwm_Value'):
  pruio_pwm_Value = _libs['pruio'].pruio_pwm_Value
  pruio_pwm_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_pwm_Value.restype = ReturnString
  else:
    pruio_pwm_Value.restype = String
    pruio_pwm_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 246
if hasattr(_libs['pruio'], 'pruio_pwm_setValue'):
  pruio_pwm_setValue = _libs['pruio'].pruio_pwm_setValue
  pruio_pwm_setValue.argtypes = [POINTER(PruIo), UInt8, Float_t, Float_t]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_pwm_setValue.restype = ReturnString
  else:
    pruio_pwm_setValue.restype = String
    pruio_pwm_setValue.errcheck = ReturnString

# pruio_c_wrapper.bas: 259
if hasattr(_libs['pruio'], 'pruio_tim_Value'):
  pruio_tim_Value = _libs['pruio'].pruio_tim_Value
  pruio_tim_Value.argtypes = [POINTER(PruIo), UInt8, POINTER(Float_t), POINTER(Float_t)]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_tim_Value.restype = ReturnString
  else:
    pruio_tim_Value.restype = String
    pruio_tim_Value.errcheck = ReturnString

# pruio_c_wrapper.bas: 272
if hasattr(_libs['pruio'], 'pruio_tim_setValue'):
  pruio_tim_setValue = _libs['pruio'].pruio_tim_setValue
  pruio_tim_setValue.argtypes = [POINTER(PruIo), UInt8, Float_t, Float_t, UInt16]
  if sizeof(c_int) == sizeof(c_void_p):
    pruio_tim_setValue.restype = ReturnString
  else:
    pruio_tim_setValue.restype = String
    pruio_tim_setValue.errcheck = ReturnString
